// Generated by https://quicktype.io

import { BookingSeat } from "./BookingSeat";
import { Trip } from "./Trip";

export type Booking = {
    tripId: number;    
    trip: Trip;
    bookingSeats: BookingSeat[];
}


