// Generated by https://quicktype.io
import { Route } from './Route.ts';
import { Seat } from './Seat.ts';

export type Trip = {
    tripId:       number;
    departure:    string;
    pricePerSeat: number;
    trainId:      number;
    route:        Route;
    seats:        Seat[];
}

export enum Position {
    A = "A",
    B = "B",
    C = "C",
    D = "D",
}
